server:
  port: 8080
spring:
  application:
    name: "nodemanagementservice "
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/nodemanagementservicedb
    username: root
    password: root
  jpa:
    show-sql: false
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO